/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncLoader: typeof import('./../components/AsyncLoader.vue')['default']
    ChatPanel: typeof import('./../components/ChatPanel.vue')['default']
    ComposerPanel: typeof import('./../components/ComposerPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    HomePage: typeof import('./../components/HomePage.vue')['default']
    KnowledgeBasePage: typeof import('./../components/KnowledgeBasePage.vue')['default']
    KnowledgePanel: typeof import('./../components/KnowledgePanel.vue')['default']
    MessageCard: typeof import('./../components/MessageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionPanel: typeof import('./../components/SessionPanel.vue')['default']
    SidebarPanel: typeof import('./../components/SidebarPanel.vue')['default']
    TopBar: typeof import('./../components/TopBar.vue')['default']
  }
}
