/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentTimeline: typeof import('./../components/AgentTimeline.vue')['default']
    ChatPanel: typeof import('./../components/ChatPanel.vue')['default']
    ComposerPanel: typeof import('./../components/ComposerPanel.vue')['default']
    DocumentViewerDialog: typeof import('./../components/knowledge/DocumentViewerDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HomePage: typeof import('./../components/HomePage.vue')['default']
    KnowledgeBasePage: typeof import('./../components/KnowledgeBasePage.vue')['default']
    KnowledgeDocumentList: typeof import('./../components/knowledge/KnowledgeDocumentList.vue')['default']
    LiteratureSearchPanel: typeof import('./../components/knowledge/LiteratureSearchPanel.vue')['default']
    MessageCard: typeof import('./../components/MessageCard.vue')['default']
    ResearchResultCards: typeof import('./../components/knowledge/ResearchResultCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./../components/TopBar.vue')['default']
  }
}
